#!/bin/bash

pushd lambda
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bin/main main.go
pushd bin
zip -r - * > ../../build/lambda.zip
popd && popd

aws lambda update-function-code \
    --function-name lendingclub-auto-withdrawl \
    --zip-file fileb://./build/lambda.zip
    --runtime go1.x \
    --handler main \
    --role arn:aws:iam::<Account>:role/<Role> \
    --environment Variables="{INVESTOR_ID=<LendingClubAccountID>,LENDING_CLUB_API_KEY=<LendingClubAPIKey>}"
